- name: Import Golang Common role
  include_role:
    name: common
    tasks_from: golang
- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter
